import '@/common/string'

export { getFirstItem } from '@/common/object/getFirstItem'
export { getFirstKey } from '@/common/object/getFirstKey'
export { getLastItem } from '@/common/object/getLastItem'
export { getLastKey } from '@/common/object/getLastKey'
export { hasKey } from '@/common/object/hasKey'
export { toArray } from '@/common/object/toArray'
export { cache } from '@/common/cache'
export { deepCopy } from '@/common/deepCopy'
export { getCallbackArguments } from '@/common/getCallbackArguments'
export { getFirstVal } from '@/common/getFirstVal'
export { getLastVal } from '@/common/getLastVal'
export { getLength } from '@/common/getLength'
export { has } from '@/common/has'
export { hasGetIndex } from '@/common/hasGetIndex'
export { pluck } from '@/common/pluck'

export { getType } from '@/type/getType'
export { isEmpty } from '@/type/isEmpty'
export { isFloat } from '@/type/isFloat'
export { isRealNaN } from '@/type/isRealNaN'
export { isSet } from '@/type/isSet'
export { reportExceptType } from '@/type/reportExceptType'
export { toNumber } from '@/type/toNumber'
export { toObject } from '@/type/toObject'
export { typeofStr } from '@/type/typeofStr'

export { decodeUrl } from '@/url/decodeUrl'
export { encodeUrl } from '@/url/encodeUrl'
export { getCurrentUrlParam } from '@/url/getCurrentUrlParam'
export { getCurrentUrlParams } from '@/url/getCurrentUrlParams'
export { setCurrentUrlParams } from '@/url/setCurrentUrlParams'
export { getUrlParam } from '@/url/getUrlParam'
export { getUrlParams } from '@/url/getUrlParams'
export { setUrlParams } from '@/url/setUrlParams'

export const version: string = '1.6.0'
