import '@/common/string.ts'

export { getFirstItem } from '@/common/object/getFirstItem.ts'
export { getFirstKey } from '@/common/object/getFirstKey.ts'
export { getLastItem } from '@/common/object/getLastItem.ts'
export { getLastKey } from '@/common/object/getLastKey.ts'
export { hasKey } from '@/common/object/hasKey.ts'
export { toArray } from '@/common/object/toArray.ts'
export { cache } from '@/common/cache.ts'
export { deepCopy } from '@/common/deepCopy.ts'
export { getCallbackArguments } from '@/common/getCallbackArguments.ts'
export { getFirstVal } from '@/common/getFirstVal.ts'
export { getLastVal } from '@/common/getLastVal.ts'
export { getLength } from '@/common/getLength.ts'
export { has } from '@/common/has.ts'
export { hasGetIndex } from '@/common/hasGetIndex.ts'
export { pluck } from '@/common/pluck.ts'

export { getType } from '@/type/getType.ts'
export { isEmpty } from '@/type/isEmpty.ts'
export { isFloat } from '@/type/isFloat.ts'
export { isRealNaN } from '@/type/isRealNaN.ts'
export { isSet } from '@/type/isSet.ts'
export { reportExceptType } from '@/type/reportExceptType.ts'
export { toNumber } from '@/type/toNumber.ts'
export { toObject } from '@/type/toObject.ts'
export { typeofStr } from '@/type/typeofStr.ts'

export { decodeUrl } from '@/url/decodeUrl.ts'
export { encodeUrl } from '@/url/encodeUrl.ts'
export { getCurrentUrlParam } from '@/url/getCurrentUrlParam.ts'
export { getCurrentUrlParams } from '@/url/getCurrentUrlParams.ts'
export { setCurrentUrlParams } from '@/url/setCurrentUrlParams.ts'
export { getUrlParam } from '@/url/getUrlParam.ts'
export { getUrlParams } from '@/url/getUrlParams.ts'
export { setUrlParams } from '@/url/setUrlParams.ts'

export const version: string = '1.6.0'
